// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4OMXFjbR1stASpXKD_ODd41cBmDyS-h0',
    appId: '1:963927956143:web:7dcc11743b3d5bcef0125a',
    messagingSenderId: '963927956143',
    projectId: 'tasty-delights-a623f',
    authDomain: 'tasty-delights-a623f.firebaseapp.com',
    storageBucket: 'tasty-delights-a623f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALGmO26GZhUUYc3FxKkBamuS-X3QkabEU',
    appId: '1:963927956143:android:19a9f808670bf88ff0125a',
    messagingSenderId: '963927956143',
    projectId: 'tasty-delights-a623f',
    storageBucket: 'tasty-delights-a623f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLJAVI-MCfBqfjV43JLCMYtIG5FCuwY8M',
    appId: '1:763604610836:ios:2776c6fdcace567b56dc01',
    messagingSenderId: '763604610836',
    projectId: 'tasty-delights-3d745',
    storageBucket: 'tasty-delights-3d745.firebasestorage.app',
    iosBundleId: 'com.example.tastyDelights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLJAVI-MCfBqfjV43JLCMYtIG5FCuwY8M',
    appId: '1:763604610836:ios:2776c6fdcace567b56dc01',
    messagingSenderId: '763604610836',
    projectId: 'tasty-delights-3d745',
    storageBucket: 'tasty-delights-3d745.firebasestorage.app',
    iosBundleId: 'com.example.tastyDelights',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4OMXFjbR1stASpXKD_ODd41cBmDyS-h0',
    appId: '1:963927956143:web:638fd667c3e053d3f0125a',
    messagingSenderId: '963927956143',
    projectId: 'tasty-delights-a623f',
    authDomain: 'tasty-delights-a623f.firebaseapp.com',
    storageBucket: 'tasty-delights-a623f.firebasestorage.app',
  );

}